import Mathlib

open scoped BigOperators

namespace AffineSectionLogRank

/-- Swapping two coordinates with unequal weights changes the value of an
affine form on a uniform layer.  This is the local, axiom-free core of the
affine support-gap pairing used by the anchor-free sparse HLS theorem. -/
theorem affine_swap_values_ne
    {α : Type*} [Fintype α] [DecidableEq α]
    (constant : ℝ) (weight : α → ℝ) {x y : α}
    (hweight : weight x ≠ weight y)
    (U : Finset α) (hxU : x ∉ U) (hyU : y ∉ U) :
    constant + ∑ z ∈ insert x U, weight z ≠
      constant + ∑ z ∈ insert y U, weight z := by
  intro h
  rw [Finset.sum_insert hxU, Finset.sum_insert hyU] at h
  apply hweight
  linarith

/-- In each swap pair generated by unequal coordinate weights, at least one
affine value is nonzero. -/
theorem affine_swap_one_ne_zero
    {α : Type*} [Fintype α] [DecidableEq α]
    (constant : ℝ) (weight : α → ℝ) {x y : α}
    (hweight : weight x ≠ weight y)
    (U : Finset α) (hxU : x ∉ U) (hyU : y ∉ U) :
    constant + ∑ z ∈ insert x U, weight z ≠ 0 ∨
      constant + ∑ z ∈ insert y U, weight z ≠ 0 := by
  by_contra h
  push_neg at h
  exact affine_swap_values_ne constant weight hweight U hxU hyU (h.1.trans h.2.symm)

end AffineSectionLogRank
